apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk004-stock-api
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk004-stock-api
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 371460792541b8e16b54898d473ad66e
      labels:
        app: sk004-stock-api
    spec:
      serviceAccountName: default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: control-plane
                operator: In
                values:
                - "amdp"
      containers:
      - name: stock-api
        image: amdp-registry.skala-ai.com/skala25a/sk004-stock-api@@sha256:48709f1f61dfed5853bcbea220e0e485b61682b8bfb550d9d8d38f57fe90c17f
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk004
        - name: NAMESPACE
          value: skala-practice
      tolerations:
      - effect: 
        key: control-plane
        operator: Equal
        value: "amdp"
