apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skala-004-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public-nginx
  rules:
  - host: springboot.skala25a.project2.skala-ai.com
    http:
      paths:
      - path: /actuator
        pathType: Prefix
        backend:
          service:
            name: sk004-stock-api
            port:
              number: 8080
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: sk004-stock-api
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sk004-stock-api
            port:
              number: 8080
      - path: /ui
        pathType: Prefix
        backend:
          service:
            name: sk004-stock-ui
            port:
              number: 8080
  tls:
  - hosts:
    - '*.skala25a.project.skala-ai.com'
    secretName: skala25-project-tls-cert