apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skala-004-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: skala004.stock.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sk004-stock-api
            port:
              number: 8080